import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Tishya Jha | Space Portfolio",
  description: "Welcome to Tishya Jha's full stack Next.js 14 space portfolio. B.Tech CSE student at RGIPT with expertise in AI, ML, and web development.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "space-portfolio",
    "portfolio",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
    "ai",
    "machine-learning",
    "python",
    "fastapi",
    "postgresql",
    "rgipt",
    "computer-science",
  ] as Array<string>,
  authors: {
    name: "Tishya Jha",
    url: "https://github.com/TishyaJ",
  },
} as const;
